// Generated by CoffeeScript 1.7.1
define(function(require) {
	return function(app) {
		app.run([ '$rootScope','Announcement',   '$http','GeneratedKey','UploadFile','ProvCode',
	      function($rootScope,  Announcement,     $http,  GeneratedKey,  UploadFile,  ProvCode) {
					if (!sessionStorage.length || !sessionStorage.logName || !sessionStorage.id) {//
						alert('用户信息已失效,请您重新登录系统!')
						location.href = 'login.html';
					}
		        	$rootScope.formatNumber = function(number){
		        		number = '' + number;
		        		return number.replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");
		        	}
					//查看公告详细信息
					$rootScope.toDetail = function(announcement){
		        		$rootScope.announcement = angular.copy(announcement) || new Announcement;
		        		
		        	};
		        	
		         
		        	
		        	//查看公告
		        	Announcement.query({isArray : true,params:{
							annoState:2
						}}, function(list){
							$rootScope.announceNumber = list.length;
							$rootScope.announceList = list;
					});

		        	ProvCode.query({isArray:true,params:{}},function (list) { // for combo
		        		$rootScope.provList = list;
		            });

		        	
		        	$rootScope.updateclinic = function(key){
		        		//add and edit
		            	 $rootScope.tempitem = angular.copy(key);
		                		   $rootScope.keys = GeneratedKey.post({
		                               optype : "genKeyN",
		                               n : 2
		                           },function(result){                    
		                				 var newids = result.newIds.split(",");  
		                				 var ids= "";
		                				 if($rootScope.tempitem.clinicPic && $rootScope.tempitem.clinicLicense){
		                					 ids = "'"+$rootScope.tempitem.clinicPic+"','"+$rootScope.tempitem.clinicLicense+"'";
		                				 }else if($rootScope.tempitem.clinicPic){
		                					 ids="'"+$rootScope.tempitem.clinicPic+"'";
		                				 }else if($rootScope.tempitem.clinicLicense){
		                					 ids="'"+$rootScope.tempitem.clinicLicense+"'";
		                				 }
		                                 }
		                    	      ); 
		        	}
		        	$rootScope.imgShow = function(fileId){ 
		            	   if(!fileId){
		            		   return;
		            	   }
		            	   var pathName = window.document.location.pathname;
		            	   var projectName = pathName.substring(0, pathName.substr(1).indexOf('/')+1);

		             	   return projectName+'/uploadFile.shtml?method=download&fileId='+fileId; 
		             	}
		        	
		        	$rootScope.showEditPswd = function(){
		        		$('#clinicedit').modal('hide');
		        		$('#editUserPwd').modal('show');
		        	}
                    //报表地址
                    $rootScope.resultPath = seajs.data.data.resultPath;

					$rootScope.USER_INFO = angular.copy(sessionStorage);//

					$rootScope.USER_INFO.institution = angular.fromJson($rootScope.USER_INFO.institution) || {};
					
					$rootScope.logout = function() {//
						
						$http({
							method : 'post',
							url : 'auth.shtml',
							data : {
								logout : true
							}
						}).success(function(result) {
							
							if (result.success === "false") {
								alert(result.message)
							} else {
								sessionStorage.clear();
//								$timeout(function() {
									location.href = 'login.html';
//								}, 1);
							}
						});

					};
				} ]);
		app.controller('RePasswordCtrl', [ '$scope','User', function($scope,User) {
				$scope.user = new User($scope.USER_INFO);
				$scope.send = function(){
					User.post({
						pwd:true,
						userId:$scope.user.id,
						oldPwd:$scope.oldpwd,
						newPwd:$scope.newpwd
					},function(result){
						if(result.success==='false'){
							alert(result.message);
						}else{
							 
							$scope.logout();
						}
					});
				}
		} ]);

		app.controller('UpdateUserCtrl', [ '$scope','$rootScope','User',  function($scope,$rootScope,User) {
				var tmp = $scope.USER_INFO;
				$scope.user = new User({
					id : tmp.id,
					userName : tmp.userName,
					email : tmp.email,
					phone : tmp.phone
				});
				$scope.updateUser=function(){
					User.save($scope.user, function(result){
						if(result.success === 'false'){
							alert(result.message);
						}else{
							 
		    				sessionStorage.userName = $scope.user.userName;
		    				sessionStorage.email = $scope.user.email;
		    				sessionStorage.phone = $scope.user.phone;
		    				$rootScope.USER_INFO = angular.copy(sessionStorage);//
						}
					})
				}
		} ]);
	}
});
